### ISSUE TITLE
Cookies Required Problem

### ISSUE THREAD

**Issue by ghost** [Athlon1600/php-proxy-app#10]
Hi Athlon, 
I am a user in China, because of GFW, I need to use your app for facebook.com, how even, when i try to log into Facebook, i get the error below:

> Cookies Required
> Cookies are not enabled on your browser. Please enable cookies in your browser preferences to continue.

So how can i fix?

**Comment by Athlon1600** [comment]
This needs a special plugin just for Facebook which is in the works right now.
