### ISSUE TITLE
Do cookies work?

### ISSUE THREAD

**Issue by Benji-Collins** [Athlon1600/php-proxy-app#101]
I haven't noticed whether they do or not. Just curious.

**Comment by Athlon1600** [comment]
They should. That's what this plugin is for:  
https://github.com/Athlon1600/php-proxy/blob/master/src/Plugin/CookiePlugin.php  
  
and it is enabled by default when php-proxy-app is installed:  
https://github.com/Athlon1600/php-proxy-app/blob/master/config.php#L27
