### ISSUE TITLE
No log file

### ISSUE THREAD

**Issue by LilChickenz** [Athlon1600/php-proxy-app#102]
Hey, so I'm trying to use the log file and ive put it in the plugins folder as well as add it to the config.php. I don't get any errors when i try and use the site but I've checked and there is no log file created

**Comment by Athlon1600** [comment]
Are you using the LogPlugin from here:  
https://github.com/Athlon1600/php-proxy-plugin-bundle/blob/master/src/LogPlugin.php  
  
?
