### ISSUE TITLE
hide .php extension

### ISSUE THREAD

**Issue by zorrigas** [Athlon1600/php-proxy-app#104]
Any option to hide .php extension on index? some firewalls block .php on url, i tried with htaccess, but get loop redirection.

**Comment by zorrigas** [comment]
yep, block when url have .php, i tried hide extension with htaccess, but only work with index, when proxy send url this is redirected to index.php again, and firewall block request.

**Comment by zpit367** [comment]
I know there is a way with wampserver/apache dont remember offhand tho

**Comment by zorrigas** [comment]
Fixed, now is working, i can post the changes on the night.
