### ISSUE TITLE
Could you please provide an option to hide the header?

### ISSUE THREAD

**Issue by Zxilly** [Athlon1600/php-proxy-app#107]
Somtimes it block some important part on pages.

**Comment by Athlon1600** [comment]
Couldn't you just remove UrlForm plugins from the list of plugins that get loaded:  
https://github.com/Athlon1600/php-proxy-app/blob/master/config.php#L29  
  
^ that's what adds that top bar.

**Comment by Zxilly** [comment]
thanks
