### ISSUE TITLE
[Question] How do I add a custom player?

### ISSUE THREAD

**Issue by TheRealZagon** [Athlon1600/php-proxy-app#109]
How can I add a custom player (Ex: Video.js) when a video is played on the proxy?

Example:
[https://unblocked.lol/YouTube.php](https://unblocked.lol/YouTube.php)

**Comment by ash121121** [comment]
this is my site :)

**Comment by TheRealZagon** [comment]
Thank you! It worked.
Btw, I love your site :)

**Comment by chronic0383** [comment]
How do you change/add the new html5 player, to the mentioned utils.php I'm a little unsure how to add the jsplayer? Any help or point in the direction would be amazing.
