### ISSUE TITLE
[Question] How can I block a website?

### ISSUE THREAD

**Issue by TheRealZagon** [Athlon1600/php-proxy-app#111]
How can I block certain pages  (Ex: netflix.com) so no one can access them?
I was receiving a lot of Netcraft takedown notices because of someone trying to access Netflix.

pls help

**Comment by ash121121** [comment]
Contact me on skype if you have it

**Comment by Athlon1600** [comment]
https://github.com/Athlon1600/php-proxy/blob/master/src/Plugin/BlockListPlugin.php
