### ISSUE TITLE
Bypassing cloudflare protection

### ISSUE THREAD

**Issue by chronic0383** [Athlon1600/php-proxy-app#116]
Limetorrents have moved to cloudflare, I believe they have enabled browser check, or header check when you go to download the actual torrent, at the moment the proxy fails with 503 error. Any help would be great or I can pay for someone's time to help build a plugin.

**Comment by ash121121** [comment]
I can bypass it on my own custom proxy script but i havent tested on php-proxy

**Comment by chronic0383** [comment]
Hi Ash, looks like limetorrents have made some adjustments today which has fixed the issue. Thank you for replying though. Your Script is freaking amazing, seems to get past everything :), was looking at your site last night, fair play to you buddy.

**Comment by chronic0383** [comment]
Sorry looks like the issue is back :(, i found your plugin for removing the cloudflare header, which is amazing by the way. Any ideas or fancy selling a way to enable torrent sites to be unblocked ?

**Comment by ash121121** [comment]
Can you tell me what site your having issue with proxying ?

**Comment by chronic0383** [comment]
Hi buddy it's Limetorrents.cc I can load the site fine thanks to your cloudflare plugin, but when ever you like a torrent download or mirror it throughs a 503 error, I'm sure it's something cloudflare based.

**Comment by ash121121** [comment]
Contact me by email mate easier for me . unblockedlol@protonmail.com

**Comment by chronic0383** [comment]
Ok buddy, will email you in a few mins
