### ISSUE TITLE
Plugin that forces Reddit to use the old design?

### ISSUE THREAD

**Issue by Benji-Collins** [Athlon1600/php-proxy-app#117]
Reddit is switching from its classic, well known design to a new, more modern design. While this design is (arguably) nice, it doesn't work when proxified. Has anyone made/could someone please make a plugin that will force Reddit to use its old design?

**Comment by ash121121** [comment]
Maybe try sending an old useragent ?

**Comment by Athlon1600** [comment]
just use https://old.reddit.com/
