### ISSUE TITLE
google.com error 503

### ISSUE THREAD

**Issue by Villivateur** [Athlon1600/php-proxy-app#119]
![image](https://user-images.githubusercontent.com/30222160/43467264-efce4fc8-9513-11e8-8f3e-7165790ca548.png)
When using php-proxy to visit google.com, and search for something, it always returns 503.
I am using nginx with php7.0.
When visiting other websites such as bing.com, no error occurs.

**Comment by ash121121** [comment]
I found using a proxy ip fixes this. Could be google blocking your ip
