### ISSUE TITLE
Google Analytics / Javascript not loading

### ISSUE THREAD

**Issue by Prafful10** [Athlon1600/php-proxy-app#121]
When url is open via proxy page, Google analytics is not loading in the page and same can be verified by checking network request. Is there a way i can load Google Analytics in the page?
Any support will be helpful. Thanks.

**Comment by ash121121** [comment]
If you use cloudflare you can install analytics in apps section

**Comment by 365cent** [comment]
Put your tracking code here: templates/url_form.php
Also, you can take a look at my template:https://github.com/365cent/365
