### ISSUE TITLE
Block All Websites Except Some?

### ISSUE THREAD

**Issue by bionichuman** [Athlon1600/php-proxy-app#122]
Is it possible to Block All Websites Except Some? Like stop people from being able to use the proxy for example.com but allow google.com?

I used this but it blocked scripts and sub domains too. 

// decode q parameter to get the real URL
$url = url_decrypt($_GET['q']);
if(!preg_match('/(cnn\.com)|(facebook\.com)/', $url)){
    exit;
}
$proxy = new Proxy();

**Comment by Athlon1600** [comment]
use this:  
https://github.com/Athlon1600/php-proxy/blob/master/src/Plugin/BlockListPlugin.php
