### ISSUE TITLE
Force SSL?

### ISSUE THREAD

**Issue by ghost** [Athlon1600/php-proxy-app#127]
Is there a way to force all URLs to use https no matter what? Some of the links are rendered with http, which causes images and resources to not load:

![image](https://user-images.githubusercontent.com/43509032/46250803-9e00ef80-c3f7-11e8-90f2-92c9597e0a49.png)

**Comment by IntifiPixel** [comment]
Create a .htaccess file in the directory that has PHP proxy in it and put this code in it
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
It forces the user to use https instead of http. Good luck!
