### ISSUE TITLE
CURLOPT_PROXY socks5,(56) Proxy CONNECT aborted

### ISSUE THREAD

**Issue by whoamidemo** [Athlon1600/php-proxy-app#137]
my config.php

$config['curl'] = array(
	   CURLOPT_ENCODING => 'gzip',
     CURLOPT_PROXY => 'IP:1080',
     CURLOPT_PROXYTYPE => 'CURLPROXY_SOCKS5',
     CURLOPT_PROXYUSERPWD => 'user:password',

(56) Proxy CONNECT aborted

**Comment by whoamidemo** [comment]
Unable to use socks5.

**Comment by ceojazzy** [comment]
did you manage to do it?
