### ISSUE TITLE
DANGEROUS INSTRUCTIONS ON https://www.php-proxy.com/

### ISSUE THREAD

**Issue by BillyParadise** [Athlon1600/php-proxy-app#14]
I hope you guys are not associated with these server-wrecking instructions!!!!

it will destroy any subdirectories of /var/www on its installation script.

 bash <(wget -O - https://raw.githubusercontent.com/Athlon1600/php-proxy-installer/master/install.sh)

**Comment by MitchTalmadge** [comment]
That's pretty terrifying. It deletes all files under /var/www/ and removes all Apache sites-enabled and sites-available entries.

**Comment by Athlon1600** [comment]
This should fix that: https://github.com/Athlon1600/php-proxy-installer/commit/eeebc9acfbafc07001c4c1f91e837313609a4e77
