### ISSUE TITLE
PHP-Proxy ver<=5.1.0 have Cross-Site Scripting (XSS) Vulnerability

### ISSUE THREAD

**Issue by eddietcc** [Athlon1600/php-proxy-app#140]
PHP-Proxy before 5.1.0 has Cross-Site Scripting (XSS) via the URL field in `index.php`.
Ref. https://github.com/eddietcc/CVEnotes/blob/master/PHP-Proxy/RADME.md

![](https://github.com/eddietcc/CVEnotes/raw/master/PHP-Proxy/png/2.png)
![](https://github.com/eddietcc/CVEnotes/raw/master/PHP-Proxy/png/3.png)

**Comment by Benji-Collins** [comment]
Holy shit there’s a lot of vulnerabilities going around.

**Comment by Athlon1600** [comment]
This should fix it:  
https://github.com/Athlon1600/php-proxy-app/commit/f74d9315ded7c05030023efcbedbcb24e8cc3a64
