### ISSUE TITLE
hide user ip

### ISSUE THREAD

**Issue by oft-fkg** [Athlon1600/php-proxy-app#144]
hi, when i request [httpbin.org/ip](http://httpbin.org/ip) it returns `{"origin" : "user-ip, server-ip"}`

how can i hide the user ip ? i tried the demo in the project page and it doesnt show the user ip.

thnaks

**Comment by oft-fkg** [comment]
looking at [this](http://www.vermiip.es/show-my-ip/) page i think that the problem is the `HTTP_X_FORWARDED_FOR` header. i tried to remove it with a plugin but it doesnt even show.

does anyone knows how to delete it ? maybe is somethig else ?

**Comment by Athlon1600** [comment]
the only headers  that are being forwarded from the client to the destination server are these:
https://github.com/Athlon1600/php-proxy/blob/master/src/Plugin/HeaderRewritePlugin.php#L43  
  
^ maybe you have that plugin disabled on your php proxy installation?
