### ISSUE TITLE
Session is not preserved

### ISSUE THREAD

**Issue by aglim** [Athlon1600/php-proxy-app#15]
Hi,

I'm trying to use php-proxy-app for viewing site with login, but nothing happens after entering login data and pressing login button. I think this is due to cookies. 

Cookie plugin is enabled in config.

**Comment by Athlon1600** [comment]
Which website was that? It seems to work for most sites so far...

**Comment by SashaDesigN** [comment]
I have the same issue

**Comment by zpit367** [comment]
me too
