### ISSUE TITLE
Illegal Characters found in URL

### ISSUE THREAD

**Issue by kaliphx** [Athlon1600/php-proxy-app#151]
You should not link to proxy pages directly. Illegal Characters found in URL.

Above error I receive if I try to visit old.reddit.com
The website works but why do I receive this error.

**Comment by Athlon1600** [comment]
Problem with javascript. Add:  
```php

$config['js_remove'] = array('reddit.com');
```

to your config.php file here and that will fix it.
https://github.com/Athlon1600/php-proxy-app/blob/master/config.php

**Comment by kaliphx** [comment]
Thanks it works now.
