### ISSUE TITLE
CURLOPT_FOLLOWLOCATION  trouble with youtube

### ISSUE THREAD

**Issue by goxofy** [Athlon1600/php-proxy-app#157]
When open a youtube video page, it shows this
```
Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /wwwroot/vendor/athlon1600/youtube-downloader/src/YouTubeDownloader.php on line 110
```

**Comment by Athlon1600** [comment]
your server is not configured properly. Not something I can fix from my end.
https://stackoverflow.com/questions/6918623/curlopt-followlocation-cannot-be-activated
