### ISSUE TITLE
Forcing IPv4 when connecting over IPv6

### ISSUE THREAD

**Issue by dextronox** [Athlon1600/php-proxy-app#17]
Hi,

I assume it would just be as simple as adding one line into the test-plugin file, but is there a way to force the server to use IPv4 even if the web server is running over IPv6. The server has the ability to communicate via IPv4.

Thanks

**Comment by Athlon1600** [comment]
You can actually set this through config.php. Just add this line:
```php
$config['curl'] = array(
     CURLOPT_IPRESOLVE=> CURL_IPRESOLVE_V4
);
```

**Comment by dextronox** [comment]
Wonderful...pushing the update to all my servers now.
Thanks heaps!
