### ISSUE TITLE
cURL is not enabled ? well, it is

### ISSUE THREAD

**Issue by pyluyten** [Athlon1600/php-proxy-app#173]
I cloned php proxy in my html, which is powered by apache. Going to site i got "cURL extension is not loaded!".

I check this using command php -r "print_r(get_loaded_extensions());"
```
Array
(
    [0] => Core
    [1] => date
(...)
    [18] => curl

```

Apache was restarted after curl was installed. So i'm not sure where issue is. Maybe my apache config is too strict somewhere. Maybe php  version mismatch? nothing in README seems to help me.

edit : debian 10      php7.3-curl

**Comment by williamchai** [comment]
`sudo apt install php-curl` solved it for me.
