### ISSUE TITLE
Can't show thumbnail image on pornhub

### ISSUE THREAD

**Issue by 365cent** [Athlon1600/php-proxy-app#176]
Few month ago, pornhub change the way it display thumbnail. I knew disable js filter on pornhub plugin will make it work. However, I still want to block some ads from pornhub. Could you add a line of code like you did on redtube and xnxx to pornhub plugin to shift src and data-thumb_url or data-src? Thank you so much
![Annotation 2020-01-15 205208.png](https://i.loli.net/2020/01/16/hSzQP6TiXLOgjNa.png)

**Comment by nyanlinnaung** [comment]
it shows thumbnail on desktop but not on mobile for me
