### ISSUE TITLE
YouTube search bar fault

### ISSUE THREAD

**Issue by dextronox** [Athlon1600/php-proxy-app#18]
Hi,

I have recently upgraded all of my servers to the latest version of the script, however, when attempting to search on YouTube, I get redirected back to the error page. All plugins are enable in the config, and 
I have added the following to my TestPlugin.php:

$event['request']->headers->set('user-agent', 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36');

Any help would be much appreciated!
Thanks.

**Comment by Athlon1600** [comment]
This can't be right. This site: https://unblockvideos.com/ uses the last version of php-proxy, and YouTube there works just fine. Run this command in your proxy directory:  
```
composer show -i
```

and post the output

**Comment by dextronox** [comment]
Hi,
The output is the following:
`
athlon1600/php-proxy     dev-master 8ade1e9
symfony/event-dispatcher v2.8.4             Symfony EventDispatcher Component
`
Thanks!

**Comment by dextronox** [comment]
Also, might be worth noting, that on my server, when I go to search on YouTube, the suggestions list appears. However, on [unblockvideos.com](url), nothing appears. Could this be due to client side scripting?

Thanks!

**Comment by dextronox** [comment]
Nevermind, used `composer update` and there was an update available. I think the ready made download on [php-proxy.com](url) may be outdated.

Thanks!
