### ISSUE TITLE
Dont Work YouTube

### ISSUE THREAD

**Issue by KUNKUN2121** [Athlon1600/php-proxy-app#183]
When I try to watch YouTube, it says "Please update your browser" and cannot be displayed even if you press "Notify me later"

![390](https://user-images.githubusercontent.com/42810210/85851900-8e8c2180-b7ea-11ea-8717-487e5ab08b5a.png)
![392](https://user-images.githubusercontent.com/42810210/85851913-951a9900-b7ea-11ea-99be-f5286f0f6815.png)

**Comment by ch4rc0al1080** [comment]
haha, I have found the solution

**Comment by arunprasath-dev** [comment]
> 
> 
> haha, I have found the solution

Am also facing the same issue. How did you manage to fix it?

**Comment by ch4rc0al1080** [comment]
> > haha, I have found the solution
> 
> Am also facing the same issue. How did you manage to fix it?

actually it comes from reddit

just delete the cookie setting
and made the ua like you are a google bot


Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

@Athlon1600 please fix it, I can not pr now

**Comment by benjaminlammers** [comment]
> 
> 
> > > haha, I have found the solution
> > 
> > 
> > Am also facing the same issue. How did you manage to fix it?
> 
> actually it comes from reddit
> 
> just delete the cookie setting
> and made the ua like you are a google bot
> 
> Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
> 
> @Athlon1600 please fix it, I can not pr now

Can you elaborate on how you fixed the issue?  I'm having the same problem

**Comment by MapGuy11** [comment]
Still Broken Above User-Agent Doesn't Work

**Comment by ch4rc0al1080** [comment]
It broke again...I have found it...

**Comment by ch4rc0al1080** [comment]
OK I likely fixed it, but it still has some limits
First, make it like this

```php
// force old YouTube layout!
    public function onBeforeRequest(ProxyEvent $event)
    {
        //$event['request']->headers->set('Cookie', 'PREF=f6=8');
        $event['request']->headers->set('User-Agent', 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)');
    }
```

This will fix the layout in video pages etc.

Then like this

```php
//in onCompleted function
$url = $event['request']->getUrl();
		if( (!preg_match('/watch/',$url)) && (!preg_match('/results/',$url)) && (!preg_match('/feed/',$url)) && (!preg_match('/channel/',$url)) && (!preg_match('/ombed/',$url)) && (!preg_match('/css/',$url)) ) //if in the homepage
			die(header('location:index.php?q=https%3A%2F%2Fwww.youtube.com%2Ffeed%2Ftrending')); //only in url mode 0 , if you want to use it in other mode, try to post url to index.php
```

This code will direct users to the feed page which works well...

**Comment by MapGuy11** [comment]
Nevermind Got It To Work thanks! One Question Do You get 720P YouTube on your proxy when setting the resolution?

**Comment by BinBashBanana** [comment]
Thanks so much!

**Comment by ch4rc0al1080** [comment]
> Nevermind Got It To Work thanks! One Question Do You get 720P YouTube on your proxy when setting the resolution?

I replaced 480 with 720, It seems has a better quality...I'm not sure

**Comment by ch4rc0al1080** [comment]
According to the code, It seems has a priority in finding the video urls... so it might just find a .mp4 format video ...

**Comment by Athlon1600** [comment]
@kinglyl 's solution appears to be working. We're giving up on trying to make homepage load, and redirecting straight to trending page.
https://github.com/Athlon1600/php-proxy-plugin-bundle/commit/541ee4376e8d59fe5ca1b712e61a522fbf4c13b6

Now just do `composer update` and it should work, because it already works on here:
https://unblockvideos.com/

you'd have to change the logic here:
https://github.com/Athlon1600/php-proxy-plugin-bundle/blob/master/src/YoutubePlugin.php#L62

which currently works by just taking the first video it finds which happens to be **360** rather than 720.

**Comment by ch4rc0al1080** [comment]
> which currently works by just taking the first video it finds which happens to be 480 rather than 720.

```
$links = $youtube->getDownloadLinks($url, "mp4 360, mp4");
```
why 480? why not 360........

**Comment by Athlon1600** [comment]
sorry, meant to write 360 not 480. And the reason it default to such low resolution is because back when this was coded in, I had very limited bandwidth and lots of people who were using youtube, so this was the only way to not exceed my monthly bandwidth limits...

**Comment by ch4rc0al1080** [comment]
This issue can be closed now

**Comment by ch4rc0al1080** [comment]
Holy SH*T Youtube seems not working in old layout again in my site
And unblockvideos.com are facing 429 error so I don't know whither it is only my problem or not

**Comment by ch4rc0al1080** [comment]
I can see trending page in old layout, but video page is in new now

**Comment by BinBashBanana** [comment]
Maybe a cache problem? It doesn't work for me.

**Comment by ch4rc0al1080** [comment]
> I can see trending page in old layout, but video page is in new now

Now I can see video page in old layout but trending page is in new

**Comment by ch4rc0al1080** [comment]
It seems ` Html::remove_scripts() ` does't work in https://www.youtube.com and https://www.youtube.com/gaming

**Comment by BinBashBanana** [comment]
Trending page broken!

**Comment by Athlon1600** [comment]
I'm aware, but that page on youtube heavily depends on javascript and php-proxy does not parse javascript well. Hopefully I can find a solution to this...

**Comment by kinglyl** [comment]
> I'm aware, but that page on youtube heavily depends on javascript and php-proxy does not parse javascript well. Hopefully I can find a solution to this...

I found that though I have Html::remove_scripts() in Youtube plugin, it still show javascript in the home page now...but have no javascript in other page like trending and video page.
And javascript in the home page works well... but it will change the url in Address Bar

**Comment by ch4rc0al1080** [comment]
It seems that the only way to solve the problem is redirect to a specific video page
combine PREF and GoogleBot UA
```
public function onBeforeRequest(ProxyEvent $event)
    {
        $event['request']->headers->set('Cookie', 'PREF=f6=8');
        $event['request']->headers->set('User-Agent', 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)');
    }
```
and 
```
// homepage will never work properly. Redirect to trending instead.
        if (!preg_match('/(watch|results|ombed|css)/i', $url)) {
            $response->headers->set('location', proxify_url("https://www.youtube.com/watch?v=kXShLPXfWZA", $url));//you can change it 
            return;
        }
```
So users can open Youtube and find videos in the result page
