### ISSUE TITLE
Log plugin does not work

### ISSUE THREAD

**Issue by Milix-M** [Athlon1600/php-proxy-app#186]
Log plugin does not work. How does it work?

**Comment by ch4rc0al1080** [comment]
Have you create the 'storage' folder?
Have you made this folder writeable?

**Comment by Milix-M** [comment]
Created a folder in  php-proxy-app/storage and granted permissions.

**Comment by Milix-M** [comment]
I'm in a hurry and I'd appreciate it if you could do it sooner.

**Comment by ch4rc0al1080** [comment]
> 
> 
> Created a folder in php-proxy-app/storage and granted permissions.

the `storage` folder should in the same folder with the index.php

**Comment by Milix-M** [comment]
I'm only getting a partial log, why is that?

**Comment by Milix-M** [comment]
config.phpに'Log',を追加することで解決しました
