### ISSUE TITLE
youtube doesn't work only when viewed from an ipad.

### ISSUE THREAD

**Issue by Milix-M** [Athlon1600/php-proxy-app#187]
youtube doesn't work only when viewed from my ipad.What should I do?

**Comment by ch4rc0al1080** [comment]
Really? It should be unable in any deivce
youtube plugin have downed at least a month......

**Comment by Milix-M** [comment]
It's true. I can watch youtube in my environment.

**Comment by ch4rc0al1080** [comment]
I just tried the original YoutubePlugin.php and found it still can;t work...
the javascript will cause some problems in address bar

**Comment by Milix-M** [comment]
Is there a proxy that works perfectly for Youtube?

**Comment by ch4rc0al1080** [comment]
> Is there a proxy that works perfectly for Youtube?

you can try jsproxy

**Comment by Milix-M** [comment]
okay
