### ISSUE TITLE
Missing dependent Files?

### ISSUE THREAD

**Issue by kizza42** [Athlon1600/php-proxy-app#2]
Tried pulling the app zip from the website but URL is broken, Downloaded the Git repo but I seem to be missing some dependencies?

Can't find vendor/autoload.php anywhere!

PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/user/public_html/the-vellas.com/poxy/index.php on line 5

**Comment by Clevero** [comment]
there are two ways to install the web app. one way is to download the pre installed version or clone the repo with git or composer.

if you clone it via git, then you should also run "composer update" and "composer install" to install the webapp. i think the composer command in the README.md on this repo is doing the same as "git clone ..." and "composer update/install" in one thing (not tested)

have a nice day! :)

**Comment by kizza42** [comment]
Yeah, I was trying the pre installed version from https://www.php-proxy.com/php-proxy.zip but the link is broken

**Comment by Athlon1600** [comment]
It's working now:  
https://www.php-proxy.com/php-proxy.zip
