### ISSUE TITLE
Setting opt in curlopt array in config.php is ignored.

### ISSUE THREAD

**Issue by robputt796** [Athlon1600/php-proxy-app#26]
Hi,

I noticed that if I set the option...

CURLOPT_USERAGENT => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Iron/29.0.1600.1 Chrome/29.0.1600.1 Safari/537.36'

in the curl config opts array in config.php it is ignored. Is this the intended action to forward the users agent string regardless of any overriding setting in the curl opts array or is this some bug? If this is the current intended behavior should it be "inherit user's agent unless config has been set then use config"?

Let me know, maybe I'll raise a PR when I am back from vacation.

Regards,

Rob

**Comment by Athlon1600** [comment]
post the exacts contents of your config.php
