### ISSUE TITLE
The address bar is annoying when using it with Google

### ISSUE THREAD

**Issue by rayline** [Athlon1600/php-proxy-app#28]
It just covered the search input box
It is not a good idea to ask users to use Javascript to remove the bar themselves if needed

**Comment by frufin** [comment]
Not very elegant, but you may add this inside url_form.php style tag :
`.jsrp.mdm{ margin-top: 45px; }`

**Comment by whackcat** [comment]
Personally I just backed up `url_form.php` to `url_form.php.bak`, then opened `url_form.php` up and deleted everything in it.

**Comment by Athlon1600** [comment]
Yes, you'll have to modify url_form.php for all such cases.
