### ISSUE TITLE
Youtube will not always work

### ISSUE THREAD

**Issue by eob2000** [Athlon1600/php-proxy-app#29]
Some youtube videos work fine, on others the page loads but there is no player

**Comment by Athlon1600** [comment]
There is no player or the player is there but the video is not playing? If the video is not playing than that means that the URL of a video has special encryption whose algorithm changes almost every day so it is impossible for me to keep up with those updates. But the player itself should always be there. Which video is not showing a player?

**Comment by eob2000** [comment]
The player does not always appear, however I have moved to a new server and the proxy does not work at all. I will now create a new thread

**Comment by eob2000** [comment]
Reopened due to reoccurence of issue: Answering your question, yes the player only opens on certain videos, on others it does not appear, below the address bar there is just over an inch of gray and then the video title and uploader info. On other videos the player opens just fine

**Comment by Athlon1600** [comment]
send me a screenshot or the actual URL of the youtube video where this happens

**Comment by eob2000** [comment]
Just as an example:
This Works fine:
[https://www.youtube.com/watch?v=J---aiyznGQ](url)
This does not work:
[https://www.youtube.com/watch?v=GKSRyLdjsPA](url)

**Comment by Athlon1600** [comment]
Vevo videos aren't supported at the moment. You could install youtube-dl to make it work for now:  
https://github.com/Athlon1600/php-proxy/blob/master/src/Plugin/YoutubePlugin.php#L66

**Comment by eob2000** [comment]
It isnt just vevo videos, I have problems with others, for example Nyan Cat (Just as an example): https://www.youtube.com/watch?v=QH2-TGUlwu4 does not work

**Comment by Athlon1600** [comment]
ah I didn't mean to say that this only applies to Vevo videos. No, YouTube does some special encryption on ALL videos that are "monetized". So that's basically all music videos and almost every video with massive amount of views (like nyan cat). Do you have access to your VPS? If you installed youtube-dl, you wouldn't be having this problem.

**Comment by eob2000** [comment]
Ah ok,I get you. I am actually running this on an old PC in my garage so yes I have access to it, I put YouTube-DL in the plugins directory. It the proxy just goes to a white screen when I try and use it. The log mentiones that Class 'YoutubePlugin' could not be found

**Comment by Athlon1600** [comment]
you don't need to modify php-proxy here in any way. Just look at the code:  
https://github.com/Athlon1600/php-proxy/blob/master/src/Plugin/YoutubePlugin.php#L27  
  
if youtube-dl command works on that computer, it will automatically be called and its results automatically parsed by YouTubePlugin

**Comment by eob2000** [comment]
I get you, I got confused about what you meant, I will install YouTube-dl and try again

**Comment by eob2000** [comment]
I installed YouTube-DL (apt-get youtube-DL) and restarted apache. It still does not work. Do I need to restart the entire server?

**Comment by Athlon1600** [comment]
are you on windows or linux?

**Comment by eob2000** [comment]
I'm on Linux

ellis@eobws1:~$ youtube-dl
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
ellis@eobws1:~$

**Comment by Athlon1600** [comment]
I guess you would need to debug it first by editing YouTubePlugin.php:  
https://github.com/Athlon1600/php-proxy/blob/master/src/Plugin/YoutubePlugin.php#L27  

add:  
var_dump($output);
exit;

after line 28. I'm very curious what the output of that command is.

**Comment by eob2000** [comment]
I'm confused, is youtubeplugin.php meant to be in the plugins directory? When I put it in there the proxy gives error 500

**Comment by Athlon1600** [comment]
aah never mind. I just found the problem. I tried installing youtube-dl myself through apt-get and this is the error I got when I tried to download that nyan cat video:  
```shell
ERROR: Signature extraction failed: Traceback (most recent call last):"
```
it would appear that youtube-dl is out of date, but then I checked the version and it didn't match the latest version. Apt-get itself seems to be the problem because it is installing an outdated version of youtube-dl. You need to remove it, and then install it right from the official source here:  
https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl  
I just did that and everything started to work.

**Comment by eob2000** [comment]
SUCCESS! Followed the install guide on the link and it works perfectly. Thank you for all the help and for making this amazing script
