### ISSUE TITLE
Force YouTube to desktop view

### ISSUE THREAD

**Issue by TheMetaPirate** [Athlon1600/php-proxy-app#3]
I've already told you once but. Since mobile devices cannot use the proxy for watching html5 videos, currently being the only proxy I've known :), I would be really glad if you could redirect m.youtube.com videos to the desktop app.

What I do to force it to desktop is youtube.com/watch?app=desktop&persist_app=1, I hope I could help

**Comment by Athlon1600** [comment]
You can fool YouTube by changing your User-Agent to some desktop browser. Open up config.php and edit this part:

```
$config['curl'] = array(
	//CURLOPT_INTERFACE => '123.123.123.13',
	//CURLOPT_USERAGENT => 'Firefox 5000'
);
```

Uncomment the user agent part and change it to something like "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0"

**Comment by TheMetaPirate** [comment]
I've already tried that

![pic1](https://cloud.githubusercontent.com/assets/10575049/7821614/54ca67a8-03f0-11e5-9e59-2a08d19bcfe8.png)

![onbfmqa](https://cloud.githubusercontent.com/assets/10575049/7821648/8cf37642-03f0-11e5-842d-8daae3eb759e.jpg)

![ez0hwiy](https://cloud.githubusercontent.com/assets/10575049/7821740/37bddef0-03f1-11e5-8856-26d9efda7fca.jpg)

**Comment by Athlon1600** [comment]
So even with that, when you go to youtube.com, it still redirects you to m.youtube.com?

**Comment by TheMetaPirate** [comment]
Yes, and as I saw too, the iPads user-agent was in the test page.

**Comment by Athlon1600** [comment]
I'm not understand this. So is the CURLOPT_USERAGENT option ignored? What if you set it to "dfgdfgdfgdfgdf". Would you still get Mozilla Apple..?

**Comment by TheMetaPirate** [comment]
Nop, it's still says the same. I think it's not curl enough, get it xD.

**Comment by Athlon1600** [comment]
lol okay. Maybe it's an outdated version otherwise I don't know why that is not working. Is it possible for you to give me access to your server so I could do some debugging from there?

**Comment by TheMetaPirate** [comment]
Yes,I'll PM you with the data

**Comment by TheMetaPirate** [comment]
Sorry, I don't seem to find a way to PM, may you give me a email address?

**Comment by Athlon1600** [comment]
Athlon2400@gmail.com

**Comment by TheMetaPirate** [comment]
I sended you the details, don't get mad if the connection is slow, it's far away from the router, it should be stable enough

Night

**Comment by Athlon1600** [comment]
Oh never mind your server, I just tested custom curl options on my own server and it didn't work either. Here is the problem: CURLOPT_USERAGENT is being overwritten by CURLOPT_HTTPHEADER option (that includes user-agent header) - an option that you cannot override from config.php  
Ideally, setting CURLOPT_USERAGENT to something would overwrite whatever user-agent CURLOPT_HTTPHEADER was holding, but apparently this is not how php-curl works. I might send this suggestion to PHP people, to see if it makes sense to change it.  
Right now you can only change your user-agent through plugins. Edit php-proxy-app/plugins/TestPlugin.php by adding this line:

```
$event['request']->headers->set('user-agent', 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0');
```

inside onBeforeRequest method. I just tested it and it works.

**Comment by TheMetaPirate** [comment]
Oh ok, one question ,will you be implementing different user agents to be chosen with the proxy?
that would actually solve some problems in the future

**Comment by Athlon1600** [comment]
Many more things will be implemented as soon as I finish school which will be in about 2 weeks.

**Comment by TheMetaPirate** [comment]
Hmm... Adding that line just stops the proxy from loading a web page.

**Comment by Athlon1600** [comment]
Is it still not working for you?

**Comment by TheMetaPirate** [comment]
Nop, and I just rebooted and my SD Card got corrupt.

**Comment by Athlon1600** [comment]
You must have changed something else besides that line I gave you. Your proxy: http://proxy.e-education.hk/ is not working right now, so I can't check what's happening.

**Comment by TheMetaPirate** [comment]
My SD got corrupted, so the system doesn't boot anymore, I'll be setting everything up again later.

**Comment by TheMetaPirate** [comment]
ok,got in to work now. my ip is 83.59.79.21, same pass same port

**Comment by TheMetaPirate** [comment]
I'm running this proxy again at my server. But your solution for changing the user agent doesn't seem to work anymore. And I don't find a solution. Would be nice if you would help me again

**Comment by Athlon1600** [comment]
How does it not work anymore? Can you give me a link to your site and explain about what you're expecting and what you're not getting?

**Comment by TheMetaPirate** [comment]
I'm expecting it to force a user agent when the proxy fetches the page. The old solution, adding $event['request']->headers->set('user-agent', 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0'); 

Does not seem to work anymore

**Comment by Athlon1600** [comment]
What does http://whatsmyuseragent.com/ page say now?
