### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by eob2000** [Athlon1600/php-proxy-app#30]
Just installed this on my webserver (Previously worked fine on another server) and when I enter a URL I just get a white screen, does anyone have any ideas

**Comment by Athlon1600** [comment]
Yes, check the log in /var/log/apache2/ to see what it says

**Comment by eob2000** [comment]
This is the relavent thing from error.log [Sun Sep 11 19:58:51.731857 2016] [:error] [pid 19155] [client 192.168.1.1:52885] PHP Fatal error:  Uncaught Error: Call to undefined function Proxy\\Http\\mb_parse_str() in /var/www/html/proxy/vendor/athlon1600/php-proxy/src/Http/Request.php:130\nStack trace:\n#0 /var/www/html/proxy/vendor/athlon1600/php-proxy/src/Http/Request.php(50): Proxy\\Http\\Request->setUrl('http://eobnet.t...')\n#1 /var/www/html/proxy/vendor/athlon1600/php-proxy/src/Http/Request.php(304): Proxy\\Http\\Request->__construct('GET', 'http://eobnet.t...')\n#2 /var/www/html/proxy/index.php(95): Proxy\\Http\\Request::createFromGlobals()\n#3 {main}\n  thrown in /var/www/html/proxy/vendor/athlon1600/php-proxy/src/Http/Request.php on line 130, referer: http://eobnet.tk/proxy/

**Comment by Athlon1600** [comment]
You need to install mbstring extension:
http://php.net/manual/en/function.mb-parse-str.php
```shell
apt-get install php-mbstring
```

**Comment by eob2000** [comment]
it now loads but on youtube (havent checked elswhere) WHen I sear something the proxy 404s

**Comment by Athlon1600** [comment]
send me a screenshot of what you're seeing now

**Comment by eob2000** [comment]
Ok, I restarted the webserver and now I am back at my other issue with only some youtube videos working, I am going to reopen my old post and close this one, Thank you for the help
