### ISSUE TITLE
The app requests for url_form.js from php-proxy.com

### ISSUE THREAD

**Issue by rayline** [Athlon1600/php-proxy-app#33]
It is a blocking request and slows down everything, especially when your site is not reachable, for whatever reason such as firewall blocking or server down.
I think it is not needed, and we can just put that script along with the app.

**Comment by webaddicto** [comment]
I agree with this, would be good to have the .js file included in the app.

**Comment by Athlon1600** [comment]
done  
https://github.com/Athlon1600/php-proxy-app/commit/d4676fe08dff6b5aba33f1763dbf251658dd73b3
