### ISSUE TITLE
i want to use CURLOPT_PROXY but have error how to fix

### ISSUE THREAD

**Issue by karsonlam** [Athlon1600/php-proxy-app#36]
i dont have vpn server..just have proxy server.
so i  want to use CURLOPT_PROXY

    CURLOPT_PROXY => 'proxy ip',
    CURLOPT_PROXYPORT => 'proxy port',
    CURLOPT_PROXYUSERPWD => 'username:password',

just can work on first page. and will miss the PHP-Proxy bar.
how to fix it..

**Comment by Athlon1600** [comment]
Right, so you go to your config.php file and change this line to:

``
`$config['curl'] = array(CURLOPT_PROXY => 'ip:port');
```

Is it not working?

**Comment by karsonlam** [comment]
$config['curl'] = array(
CURLOPT_PROXY => 'ip:port');
CURLOPT_PROXYUSERPWD => 'username:password',
}

not working.. have bug..
1.PHP-Proxy bar will miss 
2.the link just http://www.XXXX not index.php?q=http://www.XXXX

**Comment by Athlon1600** [comment]
Send me a screenshot of what the page looks once you enable proxy

**Comment by karsonlam** [comment]
![proxy11](https://cloud.githubusercontent.com/assets/24658058/21335249/81030a5c-c698-11e6-8285-ad007552a8f1.jpg)

**Comment by karsonlam** [comment]
and the 1.PHP-Proxy bar miss

**Comment by Athlon1600** [comment]
What does your config.php look like? "UrlForm" plugin has to be ENABLED for that bar to show up.

**Comment by karsonlam** [comment]
$config['plugins'] = array(
	'HeaderRewrite',
	'Stream',
	// ^^ do not disable any of the plugins above
	'Cookie',
	'Proxify',
	'UrlForm',
	// site specific plugins below
	'Youtube',
	'DailyMotion',
	'RedTube',
	'XHamster',
	'XVideos',
	'Twitter'
);

**Comment by karsonlam** [comment]
if i use CURLOPT_INTERFACE => 'ip', the app will working...
but i dont have vpn server.. want to use proxy server

**Comment by Athlon1600** [comment]
Paste me your entire config.php file. Something is not right here. For example, link to gmail should be PROXIFIED (index.php?q=...) and right now it isn't even though ProxifyPlugin is enabled...

**Comment by karsonlam** [comment]
<?php

// all possible options will be stored
$config = array();

// a unique key that identifies this application - DO NOT LEAVE THIS EMPTY!
$config['app_key'] = '0678e02713b5ae6065c8f82df2d945af';

// a secret key to be used during encryption
$config['encryption_key'] = '';

/*
how unique is each URL that is generated by this proxy app?
0 - no encoding of any sort. People can link to proxy pages directly: ?q=http://www.yahoo.com
1 - Base64 encoding only, people can hotlink to your proxy
2 - unique to the IP address that generated it. A person that generated that URL, can bookmark it and visit it and any point
3 - unique to that session and IP address - URL no longer valid anywhere when that browser session that generated it ends
*/

$config['url_mode'] = 0;

// plugins to load - plugins will be loaded in this exact order as in array
$config['plugins'] = array(
	'HeaderRewrite',
	'Stream',
	// ^^ do not disable any of the plugins above
	'Cookie',
	'Proxify',
	'UrlForm',
	// site specific plugins below
	'Youtube',
	'DailyMotion',
	'RedTube',
	'XHamster',
	'XVideos',
	'Twitter'
);

// additional curl options to go with each request
$config['curl'] = array(
   //  CURLOPT_INTERFACE => '',
  CURLOPT_PROXY => 'ip:80',
   CURLOPT_PROXYUSERPWD => 'username:password',
    // CURLOPT_CONNECTTIMEOUT => 5
);

//$config['replace_title'] = 'Google Search';

//$config['error_redirect'] = "https://unblockvideos.com/#error={error_msg}";
//$config['index_redirect'] = 'https://unblockvideos.com/';

// $config['replace_icon'] = 'icon_url';

// this better be here other Config::load fails
return $config;

?>

**Comment by karsonlam** [comment]
i just edit  $config['curl'] = array()

other not change

**Comment by Athlon1600** [comment]
Okay, I tested this myself and it does not work for me either... weird. But I have to go to sleep now so I'll come back to this tomorrow morning.

**Comment by karsonlam** [comment]
ok good night..thanks for help

**Comment by Athlon1600** [comment]
I found the problem and it's working now:  
https://github.com/Athlon1600/php-proxy/commit/1434268abd41d45de5a6c45152927deb67bd1db5
