### ISSUE TITLE
remove HTML page titles

### ISSUE THREAD

**Issue by michi91** [Athlon1600/php-proxy-app#4]
I know this is not a real issue but unfortunately I did not find an other place to write this request. Is it possible to configure that the HTML page title will be removed because some censoring filters look at titles on HTML pages....May be it it so possible to configure a fix title for all pages like "php-proxy"....Thanks

**Comment by Athlon1600** [comment]
Done!
https://github.com/Athlon1600/php-proxy/commit/f8b93caae60fe00ef78e434798f3b53ed2b2af30

just add

```php
$config['replace_title'] = "php-proxy"
```

to your config.php file

https://github.com/Athlon1600/php-proxy-app/commit/9913405092c27d07388a12bd344853d1a63f15a6

**Comment by michi91** [comment]
Hi,
thank you for the very fast response. Unfortunately it does not works for me. Maybe I have not clear described my request.I am writing regarding the Title of the Tab e.g. in Internet Explorer. After adding your change in the config.php nothinghappens, so if I go to google via your great script, the Title is still Google instead of "php-proxy".....
Michi
Date: Sat, 18 Jul 2015 09:11:29 -0700

**Comment by Athlon1600** [comment]
That's because you're still using an outdated version of php-proxy. You need to upgrade to get the absolute latest version where I made those changes an hour ago.

**Comment by michi91** [comment]
Hi,
ah ok. Now it works....Thanks a lot for fast and great support :)
Michi

Date: Sat, 18 Jul 2015 10:03:23 -0700
