### ISSUE TITLE
youtube player

### ISSUE THREAD

**Issue by xenofx** [Athlon1600/php-proxy-app#44]
youtube player show videos 360p i think. how can I set to maximum quality for playing ? you can check proxfree.com, this script have quality option. 

Other problem is youtube videos can play but images not showing.

its main page ok.
![image](https://cloud.githubusercontent.com/assets/17323498/23402791/d56a1be0-fdb5-11e6-89a8-a5a81a6f570d.png)

its video page, images not showing.
![image](https://cloud.githubusercontent.com/assets/17323498/23402834/fc65730c-fdb5-11e6-89f6-0c6551169d6c.png)

**Comment by Athlon1600** [comment]
1) You can't do that at the moment, but I plan to add that feature really soon.

2) The images load fine for me:  
http://i.imgur.com/VyuXbSz.jpg?1  
  
can you link me to your proxy script?

**Comment by xenofx** [comment]
http://fdwnet.com/php-proxy-app/

May i change code for high quality.

**Comment by Athlon1600** [comment]
That page on your proxy seems to work for me... did you change anything since then?  
  
2) If you want all your youtube videos to appear in high quality, then you need to go to this file in your /vendor/ directory:  
https://github.com/Athlon1600/php-proxy-plugin-bundle/blob/master/src/YoutubePlugin.php  
  
and change this line:  
```php
$links = $youtube->getDownloadLinks($url, "mp4 360, mp4");
```
to this:  
```php
$links = $youtube->getDownloadLinks($url, "mp4 720, mp4 360, mp4");
```

**Comment by xenofx** [comment]
I found problem. check this picture pls> you did not encode "ytimg.com" url. some firewalls blocked this domain. need to edit, script must encode ytimg.com address.

![image](https://cloud.githubusercontent.com/assets/17323498/23449067/51b1f108-fe5d-11e6-8f28-b4f896b4074d.png)

**Comment by webaddicto** [comment]
I tested on my server and it works fine, just make sure to use the latest version of php-proxy.

**Comment by Athlon1600** [comment]
php-proxy.zip should be up-to-date now.

**Comment by xenofx** [comment]
which codes updated ?

**Comment by Athlon1600** [comment]
What do you mean by that?

**Comment by xenofx** [comment]
did you update code ? Otherwise I got it wrong? 

i said proxy script did not encode ytimg.com urls. your internet  connection did not block ytimg.com, so you can see images, but my connection blocked ytimg.com. I hope, I explain my problem now.

**Comment by Athlon1600** [comment]
You need to reinstall php-proxy by download php-proxy.zip and uploading it to your server again.

**Comment by webaddicto** [comment]
@Athlon1600 

I propose this simple PR to update php-proxy VERSION const from 4.0.1 to the latest 5.0.1:
https://github.com/Athlon1600/php-proxy/pull/53

Looks like php-proxy.zip is not yet up-to-date, I downloaded it and see this file:
php-proxy-1.zip\vendor\athlon1600\php-proxy\src\Plugin\YoutubePlugin.php

It still contains those lines of code:

```
		// --get-url
		// --dump-single-json
		$cmd = sprintf('youtube-dl -J %s', escapeshellarg($this->youtube_url));
		exec($cmd, $output, $ret);
```

It looks like the old version.

**Comment by Athlon1600** [comment]
It looks like your browser might have downloaded cached version of that zip file. I just downloaded that archive myself, and I don't even see YouTubePlugin.php inside /Plugin/ directory...

**Comment by webaddicto** [comment]
No it seems it is still the old one, type the php-proxy.zip URL:
https://www.php-proxy.com/download/php-proxy.zip

On this page (to get file MD5 hash):
http://conversion-tool.com/md5

I get this as MD5 file hash:
5eedfcfceeb282ee103a84845111c499

**Comment by Athlon1600** [comment]
Oh, I see the problem... I was download php-proxy.com/php-proxy.zip instead of php-proxy.com/**download**/php-proxy.zip. It works now.

**Comment by webaddicto** [comment]
Confirmed, it is now the new version, file MD5 hash:
d35fffdf7375ecbb41169ba93f103a54

:)

**Comment by xenofx** [comment]
Just download php-proxy.zip from this link:
https://www.php-proxy.com/download/php-proxy.zip

i download this file and extraxt to new folder but problem still continue.

**Comment by pluriglot** [comment]
@Athlon1600  I found that some proxy websites powered by PHP-Proxy can show the YouTube thumbnail images, but cannot play YouTube videos. Meanwhile, some other proxy websites powered by PHP-Proxy can play YouTube videos, but cannot show YouTube thumbnails. So, please kindly edit your PHP-Proxy script so that it can show the YouTube thumbnails and also can play the YouTube videos. I will give my support to you. Thanks!

**Comment by Athlon1600** [comment]
Already been fixed here:
https://github.com/Athlon1600/php-proxy-plugin-bundle/commit/a89e1b2329368ad0bd559b1e913cc55cedf4a51f
