### ISSUE TITLE
After install no URL working in proxy

### ISSUE THREAD

**Issue by FiveTwelveMC** [Athlon1600/php-proxy-app#45]
I've just installed everything needed, and have successfully reached the proxy page. However, when I type a URL in and press enter, I get an HTTP ERROR 500, along with this page isn't working.

The site is 149.56.98.141/sys

Thanks!

Ubuntu 16.04, Apache 2, PHP7, PHP-Proxy, PHP-Curl, all installed and up to date.

**Comment by Athlon1600** [comment]
What does the apache error log say?

**Comment by FiveTwelveMC** [comment]
The log is showing:

[Sat Mar 18 06:25:10.474450 2017] [php7:error] [pid 26012] [client 78.46.209.145:48562] script '/var/www/html/1.php' not found or unable to stat
[Sat Mar 18 06:37:27.718442 2017] [php7:error] [pid 26588] [client 130.0.232.42:55648] script '/var/www/html/judge.php' not found or unable to stat
[Sat Mar 18 06:53:48.012066 2017] [php7:error] [pid 26588] [client 130.0.232.42:46152] script '/var/www/html/judge.php' not found or unable to stat
[Sat Mar 18 07:09:18.627530 2017] [php7:error] [pid 26588] [client 45.33.86.166:46520] script '/var/www/html/gateway.php' not found or unable to stat
[Sat Mar 18 07:09:18.649296 2017] [php7:error] [pid 26015] [client 45.33.86.166:46724] script '/var/www/html/gateway.php' not found or unable to stat
[Sat Mar 18 07:09:18.672898 2017] [php7:error] [pid 26255] [client 45.33.86.166:46918] script '/var/www/html/gateway.php' not found or unable to stat
[Sat Mar 18 07:12:29.273723 2017] [php7:error] [pid 26255] [client 130.0.232.42:39800] script '/var/www/html/judge.php' not found or unable to stat
[Sat Mar 18 07:31:49.504527 2017] [php7:error] [pid 26012] [client 130.0.232.42:57416] script '/var/www/html/judge.php' not found or unable to stat
Seems like errors mostly with gateway.php and judge.php. Is this possibly an error with my installation of PHP?

**Comment by FiveTwelveMC** [comment]
Here's a new error I'm getting:

[Sat Mar 18 11:27:56.556540 2017] [php7:error] [pid 8690] [client 71.53.25.215:36426] PHP Fatal error:  Uncaught Error: Call to undefined function Proxy\\Http\\mb_parse_str() in /var/www/html/sys/vendor/athlon1600/php-proxy/src/Http/Request.php:130\nStack trace:\n#0 /var/www/html/sys/vendor/athlon1600/php-proxy/src/Http/Request.php(50): Proxy\\Http\\Request->setUrl('http://149.56.9...')\n#1 /var/www/html/sys/vendor/athlon1600/php-proxy/src/Http/Request.php(304): Proxy\\Http\\Request->__construct('GET', 'http://149.56.9...')\n#2 /var/www/html/sys/index.php(95): Proxy\\Http\\Request::createFromGlobals()\n#3 {main}\n  thrown in /var/www/html/sys/vendor/athlon1600/php-proxy/src/Http/Request.php on line 130, referer: http://149.56.98.141/sys/

**Comment by Athlon1600** [comment]
Yes, you need to install mbstring extension in your php:
http://php.net/manual/en/mbstring.installation.php

**Comment by FiveTwelveMC** [comment]
Thank you! It works now perfectly. The proxy is MUCH better than my previous Glype, appreciate it.
