### ISSUE TITLE
Proxy Server Location buttons

### ISSUE THREAD

**Issue by jahabar** [Athlon1600/php-proxy-app#47]
Hi

How do I install the Proxy Server Location fields as shown on unblockvideos.com. Is there a plugin
available for that? Also like to know about adding custom ips for visitors to use. Much appreciate your help.

Regards
Jahabar

**Comment by Athlon1600** [comment]
> How do I install the Proxy Server Location fields as shown on unblockvideos.com. Is there a plugin
available for that?

There is no plugin for that. But just look at the source code of unblockvideos.com. It's nothing but a simple HTML form that redirects each form submit to the proxy server that was chosen.

> Also like to know about adding custom ips for visitors to use.

inside the config.php file, there is an option to set custom cURL parameters to go with each proxy requests. So this is how you would do it:

```php
$config['curl'] = array(
     CURLOPT_INTERFACE => 'your_custom_ip'
);

```

**Comment by jahabar** [comment]
Hello

Thank you for your kind reply and answering my queries. I will follow up on
your advise on my site.

Thank you again

Regards
Jahabar

**Comment by jahabar** [comment]
Hi
When I access google.com from the search form from your php-proxy script
from my website
it opens google search page in the proxified page. However when I tried to
search
something from the Google.com search engine from the proxified page it
returns back
to php-proxy search form on my website and shows
*Error accessing resource: 503 - Service Unavailable*
My site is hosted on a vps

Please view screenshot attached

Thank you
Jahabar

**Comment by Athlon1600** [comment]
Google search seems to work just fine for me. Test it yourself here:  
https://unblockvideos.com/  
  
it is possible that the IP address through which your php-proxy is connecting is blocked by Google?

**Comment by schlarmanorg** [comment]
What if I was wanting to get it to select a random domain from an array?

**Comment by Benji-Collins** [comment]
@schlarmanorg create a [PHP array](https://www.w3schools.com/php/php_arrays.asp) then set it to select a value [randomly](https://www.w3schools.com/php/func_array_rand.asp).

**Comment by schlarmanorg** [comment]
@Benji-Collins Thats the thing, where exactly would that go?

**Comment by Benji-Collins** [comment]
@schlarmanorg Wherever the setting for manually changing the IP is.
