### ISSUE TITLE
Reddit issues

### ISSUE THREAD

**Issue by starsky135** [Athlon1600/php-proxy-app#48]
When visiting reddit.com on an installation, links for posts do not seems to work, rather they send the browser directly to the URL. This might be something to do with the way Reddit formats URLs (JavaScript stuff).

**Comment by Athlon1600** [comment]
I would just remove all javascript code from reddit.com. I made it easy with this new push:  
https://github.com/Athlon1600/php-proxy/commit/726f8a43f3994ee9bc23a8a80d86ce1acd371ffd  
  
Just go to your config.php file and add this line:
```php
$config['js_remove'] = array('reddit.com');
```
