### ISSUE TITLE
Ajax is not working

### ISSUE THREAD

**Issue by ahnerd** [Athlon1600/php-proxy-app#5]
Hi,
Content loaded via ajax is not showing when visiting some site with the proxy

**Comment by Athlon1600** [comment]
Which site were you visiting?

**Comment by mr0-0nerd** [comment]
Sorry for late response
Many sites i.e Youtube

**Comment by xitclub** [comment]
having same issue, load more videos, show more etc ajax functions are not working.

**Comment by domsie** [comment]
same here; is there a fix for this ajax issue?

**Comment by domsie** [comment]
Has anyone test the jquery ajax.prefilter or ajax.setup method to force the ajax links correctly?

$.ajaxSetup() - Set default values for future Ajax requests. You could, for example, set the ajax URL that you always want to use for every request here.

Example:

$.ajaxSetup({
  // Always use this URL for every request
  url: "http://example.com/ajax.php"
});
$.ajaxPrefilter() - Modify existing options before each request is sent. You could, for example, append a query string component to every ajax request that is sent out.

Example:

$.ajaxPrefilter( function(options) {
    // Always add "?debug=1" to every URL
    options.url += (options.url.indexOf("?") < 0 ? : "?" : "&") + "debug=1";
});
