### ISSUE TITLE
Undefined method 'getName'

### ISSUE THREAD

**Issue by portcomms** [Athlon1600/php-proxy-app#53]
Hi,

I have just installed via Composer. 

After a few teething problems with the session_start permissions, I created a sessions folder in the dir above the public_html folder and added the following as the first line in index.php

ini_set('session.save_path',realpath(dirname($_SERVER['DOCUMENT_ROOT']) . '/../session'));

Now when I try to load a site, I get the following error:

Fatal error: Call to undefined method Proxy\Event\ProxyEvent::getName() in /home/[user]/public_html/vendor/athlon1600/php-proxy/src/Plugin/AbstractPlugin.php on line 47

Any ideas? Thanks

**Comment by Athlon1600** [comment]
Yes, I'm aware of this issue. For now I would just use an older version of php-proxy. Go to your composer.json and change this line: 
"athlon1600/php-proxy": "~5.0.1",  
into:  
 "athlon1600/php-proxy": "5.0.1",  
and then do "composer update".

**Comment by zarzen** [comment]
Hi @Athlon1600 the modification seems not working for me.
After change the error log changed:
```
PHP Fatal error:  Uncaught Error: Call to undefined function Proxy\\Http\\mb_parse_str() in /var/www/html/php-proxy/vendor/athlon1600/php-proxy/src/Http/Request.php:130\nStack trace:\n#0 /var/www/html/php-proxy/vendor/athlon1600/php-proxy/src/Http/Request.php(50): Proxy\\Http\\Request->setUrl('http://52.168.1...')\n#1 /var/www/html/php-proxy/vendor/athlon1600/php-proxy/src/Http/Request.php(304): Proxy\\Http\\Request->__construct('GET', 'http://52.168.1...')\n#2 /var/www/html/php-proxy/index.php(95): Proxy\\Http\\Request::createFromGlobals()\n#3 {main}\n  thrown in /var/www/html/php-proxy/vendor/athlon1600/php-proxy/src/Http/Request.php on line 130
```

**Comment by zarzen** [comment]
Ok For fix in PHP7.0 we need `php7.0-mbstring`  
Install through
```
sudo apt install php7.0-mbstring
```

**Comment by Athlon1600** [comment]
Fixed in new release:  
https://github.com/Athlon1600/php-proxy/commit/12584d6892779c719d26f79bf464e7d9a2b48f88
