### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by matrixebiz** [Athlon1600/php-proxy-app#56]
Hello, I've installed the pre-installed version on my server and when I try to Proxy a website I get this error;
Fatal error: Call to undefined method Proxy\Event\ProxyEvent::getName() in /home2/matrixebiz/public_html/phpproxy/vendor/athlon1600/php-proxy/src/Plugin/AbstractPlugin.php on line 47

What should I do? also, can I run this proxy with the website direct link like: http://myserver.com/phpproxy.php?http://WebsiteNeedingProxy.com

Thanks

**Comment by Athlon1600** [comment]
Try it now:  
https://www.php-proxy.com/download/php-proxy.zip

**Comment by matrixebiz** [comment]
Okay, thank you. Now can I proxy a website by just using 1 single link, like?
http://myserver.com/phpproxy/index.php?http://WebsiteNeedingProxy.com

**Comment by matrixebiz** [comment]
... because I need to proxy a Video link as well, like;
http://myserver.com/phpproxy/index.php?http://server.com/video.m3u8

**Comment by Athlon1600** [comment]
To do all that, you would first need to edit config.php and change this line:
```php
$config['url_mode'] = 2;
```

into this:
```php
$config['url_mode'] = 0;
``` 

This is all explained at the top of that file: 
```html
how unique is each URL that is generated by this proxy app?
0 - no encoding of any sort. People can link to proxy pages directly: ?q=http://www.yahoo.com
```

Now you can link to proxified content directly like this:

`yourproxy.com/index.php?q=anotherserver.com/video.mp4`

**Comment by matrixebiz** [comment]
Okay, thanks for the info but still not working with the Roku :(
Trying to proxy http://www.myserver.com/video.m3u8 to another m3u8 and the second m3u8 file is like this;
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1000,RESOLUTION=640x360,
http://www.myserver.com/phpproxy/index.php?q=http://www.externalserver.com/playlist.m3u8?id=0ad5aac39bb13fbe54d411dc4ce8255fe785654a

Works in VLC but not the Roku :(

**Comment by Athlon1600** [comment]
If that still did not work, you should probably just use this:  
https://www.proxynova.com/proxy-software/
