### ISSUE TITLE
Can use php-proxy-app to get download link from youtube?

### ISSUE THREAD

**Issue by jamejiraju** [Athlon1600/php-proxy-app#57]
Can use php-proxy-app to get a direct link (download link) from youtube? Because some video from youtube is blocked country.  I used to https://api.unblockvideos.com/youtube_downloader?id=2UKshjz4Luo&selector=mp4&redirect=true but it return 403 error with my country. 

Please let me know how to use it like your api?

Many thanks,

**Comment by Athlon1600** [comment]
Just paste that link into your php-proxy-app installation and it should load through whatever country your server is located in. For example, go to https://unblockvideos.com/ and select a server in San Francisco - that youtube video will not be streamed from a server in America.

**Comment by jamejiraju** [comment]
Hello @Athlon1600,

I understand but I want to build api.mydomain.com which use php-proxy-app and then when I call  api.mydomain.com?id=id_youtube it will return an array which contains list link download. Example:
Array
(
    [0] => Array
        (
            [url] => Link download 720p
            [format] => MP4 720p (HD)
        )
    [1] => Array
        (
            [url] => Link download 360p
            [format] => MP4 360p
        )
)

I hope you understand my explain above and I will be very thankful to you if you can guide me.

Many thanks,

**Comment by Athlon1600** [comment]
At this point, you should just use YouTubeDownloader project directly:
https://github.com/Athlon1600/youtube-downloader

Why even bother with php-proxy-app?

**Comment by jamejiraju** [comment]
I tried it many times but my country is blocked by the video's owner and when I use  https://api.unblockvideos.com/youtube_downloader?id=2UKshjz4Luo&selector=mp4&redirect=true. It returns 403 error.  Please give a suggestion for me about it. Many thanks for your efforts.

**Comment by Athlon1600** [comment]
Okay so from what I understand, you want to route  whatever YouTube video link (https://r1---sn-vgqsknee.googlevideo.com/videoplayback?itag=22&exp....) is returned via youtube-downloader through a proxy that's located on a server that's not in one of those "blocked" countries, right?  
  
If that's what you want, then you need to use **php-proxy**:
https://github.com/Athlon1600/php-proxy  
 
And your code would look something like this:
```php

$url = 'https://www.youtube.com/watch?v=4aeETEoNfOg';

// fetch youtube video URL
$yt = new YouTubeDownloader();
$links = $yt->getDownloadLinks($url);

// not sure about current($links.... part
$response = $proxy->forward($request, current($links)['url']) );
$response->send();
```
