### ISSUE TITLE
Unknown data will be appended to the header

### ISSUE THREAD

**Issue by Dreamwatcher** [Athlon1600/php-proxy-app#59]
Hello,

when I submit a form on a website, some data appears before the first output of the index.php
![image](https://user-images.githubusercontent.com/4558876/27816640-0a5da6ca-608d-11e7-8512-038beb28449e.png)
It is everytime a 4 digit hexa code.

It looks like this string is appended at the header after the last boundary of the form fields.
Does anybody knows where this come from?

**Comment by Athlon1600** [comment]
I could not replicate this on my own end. This looks to be site specific.
