### ISSUE TITLE
Slow 

### ISSUE THREAD

**Issue by tristanS26** [Athlon1600/php-proxy-app#6]
When you type in a URL for the proxy to bring you to it is extremly slow and almost unsuable

**Comment by Athlon1600** [comment]
How fast a proxy is depends on your server and the website you're connecting to. One of my proxy apps is hosted on a fast server in San Francisco, so when I connect to youtube.com (whose servers are located near San Francisco), it's blazing fast for me. Care to post the URL to your proxy?

**Comment by tristanS26** [comment]
Its mprox.ml

**Comment by Athlon1600** [comment]
You messed up something with your configuration. How come no matter where I navigate with your proxy, my address bar still shows: http://mprox.ml/. It should be http://mprox.ml/index.php?q=....  
Also, your proxy appears to be hosted on a German server, which of course means connection to US sites will be slower, and to European sites faster than average.

**Comment by tristanS26** [comment]
How do you know it is connected to a german

**Comment by tristanS26** [comment]
And the reason for the link thing may be because mprox.ml is a redirect to mprox.dx.am

**Comment by Athlon1600** [comment]
> How do you know it is connected to a german

Visit [azenv.net](azenv.net) via your proxy. Copy the IP address. Go to whois.sc and lookup the info about that IP address such as country where it is registered in.

> And the reason for the link thing may be because mprox.ml is a redirect to mprox.dx.am

okay, yes it does appear to be slow, but maybe the problem is with your server? Try hosting it on a different server?
