### ISSUE TITLE
Doesn't load all of Youtube

### ISSUE THREAD

**Issue by NoorMkdad** [Athlon1600/php-proxy-app#62]
The Site doesnt load all of youtube, all it shows is a gray band and thats it

**Comment by schlarmanorg** [comment]
Make sure you check both repositories and make sure to check the closed section as it may have already been solved 

https://github.com/Athlon1600/php-proxy/issues/75https://github.com/Athlon1600/php-proxy/issues/75

**Comment by schlarmanorg** [comment]
https://github.com/Athlon1600/php-proxy/issues/75

**Comment by NoorMkdad** [comment]
Dang, Thanks!
