### ISSUE TITLE
Youtube issue

### ISSUE THREAD

**Issue by whois12** [Athlon1600/php-proxy-app#63]
Youtube has changed its layout that is why youtube is not running under your project.
Kindly update youtube in your project or guide us what we do in coding end.

**Comment by schlarmanorg** [comment]
Make sure you check both repositories and make sure to check the closed section as it may have already been solved 

https://github.com/Athlon1600/php-proxy/issues/75https://github.com/Athlon1600/php-proxy/issues/75

**Comment by schlarmanorg** [comment]
https://github.com/Athlon1600/php-proxy/issues/75
