### ISSUE TITLE
Dailymotion issue 

### ISSUE THREAD

**Issue by whois12** [Athlon1600/php-proxy-app#64]
Daily motion page is not displaying and also videos are not working.
It has changed layout.
![img1](https://user-images.githubusercontent.com/32157501/30794012-2f3cda72-a1df-11e7-9d64-9d2bf9f9197d.jpg)

**Comment by Athlon1600** [comment]
It's on the to-do list now:  
https://github.com/Athlon1600/php-proxy-app
