### ISSUE TITLE
web.whatsapp.net

### ISSUE THREAD

**Issue by floriansauvin** [Athlon1600/php-proxy-app#65]
https://web.whatsapp.net loads forever. I suspect something funky with .js ?

**Comment by floriansauvin** [comment]
would a plugin fix this? Did anyone encounter the same problem?

**Comment by Athlon1600** [comment]
That page is too script-heavy. Web proxies are not made for this. You should use an actual proxy server to route your browser's HTTP requests:  
https://www.proxynova.com/proxy-software/
