### ISSUE TITLE
Google.com logo issue

### ISSUE THREAD

**Issue by sam-gurdus** [Athlon1600/php-proxy-app#66]
The Google logo doesn't seem to be showing up. It looks like this: https://i.imgur.com/SCQts12.png

**Comment by Athlon1600** [comment]
go to your config.php file and add "google.com" to this list of sites already there:  

```php
$config['js_remove'] = array(
	'twitter.com', 'reddit.com', 'yahoo.com'
);
```

**Comment by samrocks9** [comment]
I don't see that section in the config.php, I am going to assume you want me to add it?

**Comment by samrocks9** [comment]
Okay, I think that worked. What does it do?

**Comment by Athlon1600** [comment]
Removes all javascript from those sites. Does google logo show up now?

**Comment by samrocks9** [comment]
Yes
