### ISSUE TITLE
Suggestion: If no TLD (.com .net etc.) is provided, enter string into Google Search

### ISSUE THREAD

**Issue by sam-gurdus** [Athlon1600/php-proxy-app#67]
Basically, if someone types 'YouTube' into the url bar of PHP-Proxy, without .com or something, it enters the term into a proxified Google Search page.

**Comment by samrocks9** [comment]
I have a lot of users that don't understand how to use the URLs, plus it would be a lot more convenient.

**Comment by Athlon1600** [comment]
link me to your site

**Comment by samrocks9** [comment]
It is http://openweb.gdn
Why do you need it?
