### ISSUE TITLE
Any way to get embeds to work?

### ISSUE THREAD

**Issue by BlohoJo** [Athlon1600/php-proxy-app#68]
Is there any way I can use this on a forum where people post youtube and twitter embeds? Right now, these just show up blank, without any kind of placeholders or anything.

**Comment by Athlon1600** [comment]
Sure, by making a special plugin that parses all those embedded objects properly. The more complex the site, the more difficult the proxification process.

**Comment by BlohoJo** [comment]
How do I do that?

Heh just kidding. ;)

**Comment by BlohoJo** [comment]
Kidding aside, I would actually try, if I had an example of something that works.

**Comment by Athlon1600** [comment]
I would look here for examples of plugins that work with searching/replacing parts that need proxifying:  
https://github.com/Athlon1600/php-proxy-plugin-bundle/tree/master/src
