### ISSUE TITLE
403 Error when enable CloudFlare protecting

### ISSUE THREAD

**Issue by Shawn-Tong** [Athlon1600/php-proxy-app#69]
I will get this error "Error accessing resource: 403 - Forbidden" if I enable CloudFlare for my site. There is no problem when I disable CloudFlare protecting.

Could you please fix this problem? Thank you very much.

**Comment by Athlon1600** [comment]
That sounds a problem with cloudflare?

**Comment by wapfalls** [comment]
Can you please provide us a way for the proxy to work through cloudflare. I am also having this issue, when cloudflare enabled.

**Comment by Athlon1600** [comment]
Can you send me the link to your proxy site?

**Comment by ash121121** [comment]
I'm having the same problem

**Comment by ash121121** [comment]
I managed to get the issue fixed for me

**Comment by wapfalls** [comment]
@ash121121 Can you plz guide us on how you managed to fix this issue?

**Comment by ash121121** [comment]
create a plugin and remove cloudflare headers

<?php

use Proxy\Plugin\AbstractPlugin;
use Proxy\Event\ProxyEvent;

class CloudflarePlugin extends AbstractPlugin {

    protected $cloudflareHeaders = array();

    public function onBeforeRequest(ProxyEvent $event){
        $event['request']->headers->set('X-Forwarded-For', $_SERVER["HTTP_CF_CONNECTING_IP"]);
        // clear Cloudflare headers
        $event['request']->headers->remove('Cf-Ray');
        $event['request']->headers->remove('Cf-Ipcountry');
        $event['request']->headers->remove('Cf-Visitor');
        $event['request']->headers->remove('Cf-Connecting-Ip');
    }
}

**Comment by ash121121** [comment]
add this plugin to remove cloudflare headers
[CloudflarePlugin.txt](https://github.com/Athlon1600/php-proxy-app/files/1650255/CloudflarePlugin.txt)

**Comment by wapfalls** [comment]
It's working!! thanks @ash121121 👍

**Comment by ash121121** [comment]
No problem

**Comment by ash121121** [comment]
So you close my fix withought a thanks ?.... what a pice of shit

**Comment by Shawn-Tong** [comment]
@ash121121 Thank you for contribution.

**Comment by ash121121** [comment]
Pfft

**Comment by systemuser1** [comment]
@ash121121, I am still trying to figure out how to use the plugin you mentioned above, can you please help me fix it. Thank you.
