### ISSUE TITLE
No website opens when hosted on vps

### ISSUE THREAD

**Issue by jheengoo** [Athlon1600/php-proxy-app#7]
Hi,

I hosted this script on shared hosting and it worked fine, but when I host it on cloud server or vps it doesn't work at all. Can you suggest something I should do to make it work?

Thanks

**Comment by Athlon1600** [comment]
Can you post the URL to your proxy?

**Comment by jheengoo** [comment]
Sorry It was me being dumb. Hadn't installed curl. It works like a charm.

-----Original Message-----
