### ISSUE TITLE
Most YouTube videos are not playing

### ISSUE THREAD

**Issue by wapfalls** [Athlon1600/php-proxy-app#70]
Hi Buddy,

Most youtube videos are not playing and shows the below error (while few are playing), Any idea on how to resolve this issue?

![you](https://user-images.githubusercontent.com/9743538/32689580-81d45fc8-c70d-11e7-9b71-12afc8da29bc.PNG)

**Comment by ash121121** [comment]
Looks like  this admin just don't care and closes issue

**Comment by ash121121** [comment]
Admin is a cunt

**Comment by Athlon1600** [comment]
That video shows up as "This video is unavailable." for me. Similar videos from that channel work fine for me though. Try it via unblockvideos.com:
https://www.youtube.com/watch?v=NkilKddoQ_U  
  
are you using the latest version of php-proxy-app?

**Comment by Athlon1600** [comment]
Appears to have been fixed.
