### ISSUE TITLE
How to install on cPanel?

### ISSUE THREAD

**Issue by TermerMC** [Athlon1600/php-proxy-app#71]
Hi, I just found out about your PHP proxy recently, and I was wondering how I could install this with cPanel on heliohost.org. Any help would be appreciated!

**Comment by ash121121** [comment]
Don't . Looks like any questions you ask her me get closed

**Comment by ash121121** [comment]
Admin why are you a Cunt

**Comment by Athlon1600** [comment]
You could download the pre-installed version of php-proxy-app and then just upload it to your web-server through whatever interface cPanel provides for that:  
https://www.php-proxy.com/download/php-proxy.zip
