### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by jcastros** [Athlon1600/php-proxy-app#74]
Please provide something similar to Glype's  Blacklist:: any site that is on the list will be blocked

**Comment by Athlon1600** [comment]
There is a BlockList plugin:  
https://github.com/Athlon1600/php-proxy/blob/master/src/Plugin/BlockListPlugin.php

enable it in your config.php file and then put this line in:  
  
```php
$config['blocklist.url_block'] = array('google.com');
```
