### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by ash121121** [Athlon1600/php-proxy-app#75]
Hey. Nice script thanks . I just installed but for some reason a lot of sites I try produce a 403 error. I've tested other proxy and they seems fine so I know it's not an ip block . Could you help me please

**Comment by ash121121** [comment]
it seems to be if you are on cloudflare and trying to proxy a cloudflare site.

**Comment by ash121121** [comment]
I solved the problem

**Comment by wapfalls** [comment]
Hi @ash121121 Can you please let us know on how you managed to fix this 403 error?

**Comment by ash121121** [comment]
Check the other post about 403 I put it there

**Comment by ash121121** [comment]
Cunt
