### ISSUE TITLE
Avoid being redirected to https

### ISSUE THREAD

**Issue by Payetus** [Athlon1600/php-proxy-app#76]
I want to avoid the redirects to https.

**Comment by ash121121** [comment]
Show an example

**Comment by Payetus** [comment]
This issue is from php-proxy not php-proxy-app. I'm closing issue in this project and reopening in php-proxy.
https://github.com/Athlon1600/php-proxy/issues/108
Also the issue can be fixed by pull request: https://github.com/Athlon1600/php-proxy/pull/109
