### ISSUE TITLE
More of a question, sorry to bother you.

### ISSUE THREAD

**Issue by Benji-Collins** [Athlon1600/php-proxy-app#77]
While going through my proxy google tells me that I should be using chrome, even though I am in chrome. Is there a setting somewhere that determines what browser the proxy shows up as?

Also, I have found that the mandatory proxy at my school blocks access to my proxy server at home. Is there a way to hide the fact that it is a proxy? Thanks.

**Comment by ash121121** [comment]
it could be that the proxy isn't sending the users user agent correctly .

**Comment by ash121121** [comment]
Send me a link to your proxy

**Comment by Benji-Collins** [comment]
It’s bcproxy.tk.

**Comment by ash121121** [comment]
im using chrome and dont see anywere on your proxy what you mentioned

**Comment by ash121121** [comment]
Why the fuck
 have u closed a genuine ask for help

**Comment by ash121121** [comment]
Admin = waste off space . Let's make a mircmsuntsuned branch

**Comment by ash121121** [comment]
Shit u can't spell . I will release a improved version of this script

**Comment by ash121121** [comment]
Sorry account hacked

**Comment by Benji-Collins** [comment]
Wtf...

**Comment by Benji-Collins** [comment]
Still interested if there is a way to hide the fact that it is a proxy while still using default web ports.

**Comment by Athlon1600** [comment]
> Also, I have found that the mandatory proxy at my school blocks access to my proxy server at home. Is there a way to hide the fact that it is a proxy? Thanks.

You should not use a web-proxy for this. Much better way would be to have something like this:
https://www.proxynova.com/proxy-software/
https://www.proxynova.com/proxy.pac  
  
As far as that Chrome problem, I can't replicate it on my end. Would you know what chrome version you are using?
