### ISSUE TITLE
The files are not loading correctly

### ISSUE THREAD

**Issue by mubbashar** [Athlon1600/php-proxy-app#8]
I visited the website. The jQuery and other files are not loading. Because they don't have full url in src. they just have relative path

https://uk1.unblockvideos.com/index.php?q=ytimptduZZLarK6S0KappKKRxmOW0dGR

Can you please look into it

thanks!

**Comment by mubbashar** [comment]
or see this http://www.abc.org.uk/
so if the webiste has relative path. it will break

**Comment by Athlon1600** [comment]
Yup. The problem was with CSS import directives that weren't "proxified". All fixed now: https://github.com/Athlon1600/php-proxy/commit/357dca4ff90e2fe3b577ff309a7743b2f9b53ac2

**Comment by mubbashar** [comment]
After download the latest Code when i run it

![screenshot 2015-08-21 18 44 48](https://cloud.githubusercontent.com/assets/378379/9409551/cb379838-4834-11e5-9911-c26fbe158604.png)
As you can see the html is loading inside js request. can you please check it . thanks!

**Comment by Athlon1600** [comment]
I can't access phpproxy.local. Can you rehost it on some public server?

**Comment by mubbashar** [comment]
let me upload on server then give you the url

**Comment by mubbashar** [comment]
http://techesthete.net/php-proxy 

please see here.

**Comment by mubbashar** [comment]
https://www.mottmac.com/ is the url that is being loaded

**Comment by Athlon1600** [comment]
I'm very confused. Are you using php-proxy-app or php-proxy alone? https://www.mottmac.com/ loads just fine on unblockvideos.com.  
If you're only using php-proxy and trying to "mirror" the output back to client, then you will need to enable "ProxifyPlugin".

**Comment by mubbashar** [comment]
Ok i configure php-proxy-app on server. It still not load relative jquery and image .
please check here 
http://techesthete.net/php-proxy/index.php?q=3Nnn5OefoqPr3Oqi4dTn6OHG1qLX1OCj

thanks!

**Comment by mubbashar** [comment]
did you check ?

**Comment by Athlon1600** [comment]
https://github.com/Athlon1600/php-proxy/commit/d9964b49e8ebf97dfabbfb8ebb813db5e7fe6fc6  
Yes, everything seems to load now with the exception of the big image at the top which probably isn't that important.

**Comment by mubbashar** [comment]
thanks for the update. It looks good now. 
I can still see some error like in original site there is a sidebar that is not showing anymore. Plus i can see the fonts are not loading. let me show you one example

https://www.dropbox.com/s/1itv6a1go9d6064/Screenshot%202015-08-25%2011.30.45.png?dl=0

**Comment by mubbashar** [comment]
Btw everything is important. it has to load everything. I hope we can make this script more and more better :)
