### ISSUE TITLE
Q: Just using it for one specific site?

### ISSUE THREAD

**Issue by MGBertie** [Athlon1600/php-proxy-app#80]
Is there a way to only allow the proxy to visit one specific site and to not allow them to use it to go to any other sites?

**Comment by Athlon1600** [comment]
Sure, check the BlockListPlugin:  
https://github.com/Athlon1600/php-proxy/blob/master/src/Plugin/BlockListPlugin.php

Putting something like this inside config.php would work:  
```php

$config['blocklist.custom'] = function($data){

     if(strpos($data['url'], "my_site.com") !== false){
          return true;
     }

     return false;
};
```

**Comment by Athlon1600** [comment]
Appears to have been solved.
