### ISSUE TITLE
Steps to enable a newly added plugin

### ISSUE THREAD

**Issue by wapfalls** [Athlon1600/php-proxy-app#81]
Hi, can you please let me know how to enable a newly added plugin.

I added a new plugin file (eg. XnxxPlugin.php) in the folder /vendor/athlon1600/php-proxy-plugin-bundle/src

now how to enable it?

**Comment by Athlon1600** [comment]
You need to add it straight to the /plugins/ folder:
https://github.com/Athlon1600/php-proxy-app/tree/master/plugins  
  
and then enable it by adding "XnxxPlugin" to this array inside config.php:  
```php
$config['plugins'] = array(
....
)
```  
  
https://github.com/Athlon1600/php-proxy-app/blob/master/config.php

**Comment by wapfalls** [comment]
Thanks @Athlon1600, I have done as you have told.

But getting the following error when opening any websites:
`Uncaught Error: Class 'XnxxPlugin' not found in /var/www/html/webproxy/index.php:88 Stack trace: #0 {main} thrown`

When i removed the namespace (`namespace Proxy\Plugin;`) from the plugin file, websites are loading but the images in the websites are not loading.

Can you please help with this.

Thanks.

**Comment by Athlon1600** [comment]
I assume it's been solved by now.
