### ISSUE TITLE
Popup 

### ISSUE THREAD

**Issue by mounirov23** [Athlon1600/php-proxy-app#82]
Hi 

in some sites , pop-up appears  , even if are not allowed in the browser , is there any way to block them ? 

Regards

**Comment by ash121121** [comment]
I made a plugin for this script that you can modify the contents of any page and remove popups very easily

**Comment by mounirov23** [comment]
ash121121
 thanks for your answer, but where could i find this plugin

**Comment by ash121121** [comment]
here you go. then just go to the sites with popups and view there source. and add stuff into the array that you would like to delete like ..
array('piratebay', 'change this', 'to this'),
[StripperPlugin.zip](https://github.com/Athlon1600/php-proxy-app/files/1729999/StripperPlugin.zip)

**Comment by wapfalls** [comment]
This plugin is really helpful!! Thanks @ash121121 👍

**Comment by ash121121** [comment]
No problem if you'd like me explain anything let me know . I also have a plugin to monetise your site with popups/ads and have a plugin that can use an array of proxy ips and store a proxy ip for a user for X amount of time using redis . It's good for sites that block your proxy

**Comment by wapfalls** [comment]
Hi @ash121121 

The comments you have mentioned on the plugin file is self explanatory and pretty clear, thanks for that.

Yes it will be very useful for everyone if you can share other plugins also or you can create a repo and share the link ☺️

**Comment by wapfalls** [comment]
Hi @ash121121, Can you please share the plugin to add popups/popunder to the proxy??

**Comment by ash121121** [comment]
Sure will put it here soon

**Comment by chronic0383** [comment]
Would be great if you could share that plugin please.

**Comment by ash121121** [comment]
Sorry I totally forgot I'll post it once I'm home

**Comment by chronic0383** [comment]
Thanks buddy that would be great 😀

**Comment by ash121121** [comment]
Np I'll put it up in around an hour

**Comment by ash121121** [comment]
[adsplugin.zip](https://github.com/Athlon1600/php-proxy-app/files/1772567/adsplugin.zip)

Here you go. any issues let me know

**Comment by chronic0383** [comment]
mate you are a star, that is amazing work thank you for sharing.

**Comment by wapfalls** [comment]
Hi @ash121121,
Thanks for the Ads plugin :) 
Unable to use Javascript ad codes with it. Any way to get it working?

**Comment by ash121121** [comment]
Seems working just fine for me

**Comment by ash121121** [comment]
Maybe your removing scripts somewhere

**Comment by chronic0383** [comment]
can you view the page source of the page, and check for the script/code. The plugin works great for me.
