### ISSUE TITLE
Some css files garbled.

### ISSUE THREAD

**Issue by toproxy** [Athlon1600/php-proxy-app#83]
hi,bro
     I found in the test moz.com this https://d2eeipcrcdle6.cloudfront.net/assets/dist/styles/moz-55f0b81a.min.css file garbled.

     
<img width="1490" alt="xx 2" src="https://user-images.githubusercontent.com/35383998/36214452-812661a8-11e4-11e8-88aa-0ba3f24eb11b.png">

**Comment by ash121121** [comment]
I've seen this happen sometimes with wrong mime or gzipped content .

**Comment by Athlon1600** [comment]
Go to your config.php, and add this line to curl section:

```php
CURLOPT_ENCODING => 'gzip'
```

should look like this:
![image](https://i.imgur.com/Hsigeef.png?1)
