### ISSUE TITLE
Searches don't work, only full URLs

### ISSUE THREAD

**Issue by Benji-Collins** [Athlon1600/php-proxy-app#84]
I have just freshly installed this to mess around with it a bit and for some reason I just get a 'Could not resolve host:' error when I just type a word in to the search, like 'youtube' for example. Full URLs, like 'www.youtube.com', work fine. Is this a known issue or has something gone wrong? My site is www.sneakysneaky.tk. Thanks.

**Comment by Benji-Collins** [comment]
I also have no encryption_key in config.php, should this be something like a password?

**Comment by relaxedricky** [comment]
> I have just freshly installed this to mess around with it a bit and for some reason I just get a 'Could not resolve host:' error when I just type a word in to the search

The box you're typing into isn't a search box, it expects a valid URL. Hence the error message and the default text within the box being "http://"

**Comment by ash121121** [comment]
Lol

**Comment by relaxedricky** [comment]
The most recent commit to this project was a year ago. So if it's something you want, looks like you'll have more luck creating your own fork and building this feature yourself.

Personally if you want to search using the proxy, use the proxy to go to a search engine.

**Comment by Benji-Collins** [comment]
You’re probably right but I’ve seen Athlon1600 hanging around so you never know. It’s not a major problem and I can just go to google.com and search. On that note, do you know of a way to automatically take the user to a site? Like auto search for google?

**Comment by zpit367** [comment]
I made a pull request that adds a search function if you want that check it out. It just checks if you entered a url and if not it makes a Google search

**Comment by Benji-Collins** [comment]
zpit367's pull request works perfectly, I highly recommend using it if you need a search function.
