### ISSUE TITLE
YouTube shows old display and tells me to get chrome

### ISSUE THREAD

**Issue by Benji-Collins** [Athlon1600/php-proxy-app#85]
I am using chrome 63, full user agent string is Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36. Other websites (like the Google homepage) seem fine.

**Comment by Athlon1600** [comment]
Can you post a screenshot of what those messages look like?

**Comment by Benji-Collins** [comment]
Here is the regular look of YouTube on Chrome:
![regular](https://user-images.githubusercontent.com/34997963/37260453-3cbbd35a-25e3-11e8-809a-ec4464688c67.PNG)

And here is what it looks like through my proxy, also using chrome:
![proxy](https://user-images.githubusercontent.com/34997963/37260452-3c8039bc-25e3-11e8-848d-b7024d9cb2ad.PNG)

While it's not an issue as far as functionality goes it's just kind of weird. The server is based in Singapore if that makes a difference but I don't see why it would. My proxy is running at www.sneakysneaky.tk.

**Comment by Athlon1600** [comment]
I think that's because YouTube plugin automatically removes all javascript from youtube pages:   
https://github.com/Athlon1600/php-proxy-plugin-bundle/blob/master/src/YoutubePlugin.php#L68  

and that's because javascript is either not working or causing extra problems.

**Comment by Benji-Collins** [comment]
Not actually an issue, it’s just how the plugin works.
