### ISSUE TITLE
Facebook videos

### ISSUE THREAD

**Issue by pluriglot** [Athlon1600/php-proxy-app#87]
@Athlon1600  Sorry to bother you! The videos on Facebook cannot be loaded on your proxy, because you did not encode/encrypt the Facebook video's URL.

Please check this site:---
https://pi.dvbris.com/public/proxy/index.php

The above-mentioned site is able to load Facebook videos because it encrypts the video's URL. Please view the below code:---
![fb video url](https://user-images.githubusercontent.com/34707208/36851088-62301f62-1da3-11e8-896c-bc6096c132a4.png)

But, unfortunately, your proxy site (https://unblockvideos.com/) does not encrypt the facebook video's URL. So, please kindly fix it.

Thank you very much!

**Comment by Athlon1600** [comment]
This will need a special plugin like we have for other sites like youtube:  
https://github.com/Athlon1600/php-proxy-plugin-bundle/tree/master/src  
  
This goes with other issues we have with facebook barely working at all:  
https://github.com/Athlon1600/php-proxy-app/issues/88  
  
I'll try fixing all that up within a few weeks.

**Comment by Athlon1600** [comment]
Facebook plugin is on my todo list now:  
https://github.com/Athlon1600/php-proxy-app#to-do-list
