### ISSUE TITLE
redirects

### ISSUE THREAD

**Issue by zpit367** [Athlon1600/php-proxy-app#89]
Im runnig it on my home pc with wampserver, and then iframing that on another site so I have a domain insteas of an Ip. The first search from the main page is great but when I try and search again from the address bar it redirects me to the Ip being iframed. how would I make it stay in the iframe?

**Comment by Athlon1600** [comment]
You're doing google searches within your web proxy that's within that frame? Probably google and most other sites don't like their pages to be embedded within other sites, so they put in scripts to prevent that. I think that's what's happening here.

**Comment by zpit367** [comment]
Oh ok thanks. Also, when I try to visit YouTube it changes depending on the
device. On one Windows PC the video looks normal and has the normal
controls. For another windows PC the video still plays like normal and fits
like normal but is missing the full screen button. Finally, on a Chromebook
when I try and use it the video is missing the full screen button and is
slightly shrunk to the top left of the video slot. What might be causing
this?

**Comment by Athlon1600** [comment]
That's because youtube.com receives a different user-agent from each of those devices and then adjusts its layout accordingly. You can override the user-agent field that gets sent from a plugin:  
https://github.com/Athlon1600/php-proxy-app/blob/master/plugins/TestPlugin.php#L9
  
just put:
```php
$event['request']->headers->set('user-agent', 'WHATEVER');
```
