### ISSUE TITLE
Accessing url has redirect loop

### ISSUE THREAD

**Issue by alimasyhur** [Athlon1600/php-proxy-app#9]
I visited some website. Some working normal, and the other has redirect loop. I've search some forum and i've no answer yet.

http://203.6.148.243/portal-journal/
(Proquest and Scopus link. This webpage has a redirect loop).
can you please take a look?
thank
#sory my bad english

**Comment by Athlon1600** [comment]
https://github.com/Athlon1600/php-proxy/issues/22
