### ISSUE TITLE
Google search returns 503 error in fr.unblockvideos.com

### ISSUE THREAD

**Issue by wapfalls** [Athlon1600/php-proxy-app#90]
Hi, 
google.com open the site, but when searched anything, it returns 503 - Service Unavailable error. It happens with the France server (fr.unblockvideos.com)

**Comment by Athlon1600** [comment]
Too many people doing google searches on that french server probably. Will be fixed once I change that server's IP address. This has nothing to do with php-proxy-app script in general though.
