### ISSUE TITLE
The YoutubePlugin.php plugin forces Youtube to use the old layout

### ISSUE THREAD

**Issue by Benji-Collins** [Athlon1600/php-proxy-app#93]
YoutubePlugin.php in /vendors/athlon1600/php-proxy-plugin-bundle/src/ forces youtube.com to use its old design. I tried changing the user agent string there to my proper modern user agent but it stops the server from being able to proxy any sites.

**Comment by zpit367** [comment]
From what I know (correct me if I'm wrong) the proxy only works if it uses
the old layout, so it's on purpose
