### ISSUE TITLE
how can i add ads to my index.php?

### ISSUE THREAD

**Issue by noldila** [Athlon1600/php-proxy-app#96]
hi, i want to add ad to my php script. how can i do that? i want to add here  (as in the picture below)
![image](https://user-images.githubusercontent.com/37547416/37604610-6e65298c-2ba2-11e8-9be4-85882cc19c5c.png)

**Comment by zpit367** [comment]
maybe this can help #82

**Comment by Athlon1600** [comment]
"Masthead AD 1" can easily be added above the address bar by simply modifying this file:  
https://github.com/Athlon1600/php-proxy-app/blob/master/templates/url_form.php#L59

Line 59 specifically. Whatever you put there, will show up above that bar.  
  
Ad2 is a bit more complicated, but for that you would have to modify the response contents before it gets sent back to the client. Check this post for an example of that:  
https://github.com/Athlon1600/php-proxy-app/issues/94#issuecomment-375991874

**Comment by ash121121** [comment]
Noldila  any luck mate ?
