### ISSUE TITLE
Is flash blocked?

### ISSUE THREAD

**Issue by Benji-Collins** [Athlon1600/php-proxy-app#98]
I thought I had flash working but after a quick test it seems to not load flash objects. My proxy is at sneakysneaky.tk.

**Comment by Athlon1600** [comment]
No, it's just that flash objects are hard to proxify. You would either have to write a special plugin for it, or you an actual proxy server:  
https://github.com/Athlon1600/php-proxy-app#web-proxy-vs-proxy-server
